<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.1 (Python 3.8.2 on linux)" generated="20200711 20:14:12.478" rpa="false">
<suite id="s1" name="Validate" source="/home/projects/Network_Infrastructure_repo/pyats/validate.robot">
<test id="s1-t1" name="Connect">
<kw name="use genie testbed &quot;${testbed}&quot;" library="genie.libs.robot.GenieRobot">
<doc>Create the genie testbed</doc>
<msg timestamp="20200711 20:14:13.528" level="INFO">+------------------------------------------------------------------------------+
|                            Genie datafiles used:                             |
+------------------------------------------------------------------------------+</msg>
<msg timestamp="20200711 20:14:13.529" level="INFO">Trigger datafile          | /usr/local/lib/python3.8/dist-packages/genie/libs/sdk/genie_yamls/iosxe/trigger_datafile_iosxe.yaml</msg>
<msg timestamp="20200711 20:14:13.529" level="INFO">Verification  datafile    | /usr/local/lib/python3.8/dist-packages/genie/libs/sdk/genie_yamls/iosxe/verification_datafile_iosxe.yaml</msg>
<msg timestamp="20200711 20:14:13.529" level="INFO">Pts datafile              | /usr/local/lib/python3.8/dist-packages/genie/libs/sdk/genie_yamls/pts_datafile.yaml</msg>
<msg timestamp="20200711 20:14:13.529" level="INFO">Subsection datafile       | /usr/local/lib/python3.8/dist-packages/genie/libs/sdk/genie_yamls/subsection_datafile.yaml</msg>
<msg timestamp="20200711 20:14:13.529" level="INFO">Config datafile           | None</msg>
<status status="PASS" starttime="20200711 20:14:13.407" endtime="20200711 20:14:14.941"></status>
</kw>
<kw name="connect to all devices" library="ats.robot.pyATSRobot">
<doc>Connect to all devices</doc>
<msg timestamp="20200711 20:14:14.942" level="INFO">Connecting to device 'Device dummy (alias=uut), type NOT REAL'</msg>
<msg timestamp="20200711 20:14:14.942" level="INFO">kwargs: {}</msg>
<msg timestamp="20200711 20:15:40.040" level="INFO">[2020-07-11 20:14:14,943] +++ dummy logfile /tmp/dummy-cli-20200711T201414942.log +++
[2020-07-11 20:14:14,944] +++ Unicon plugin iosxe +++
[2020-07-11 20:14:26,970] +++ connection to spawn: ssh 1.1.1.1, id: 140274383829792 +++
[2020-07-11 20:14:26,971] connection to dummy</msg>
<msg timestamp="20200711 20:15:40.058" level="FAIL">ConnectionError: failed to connect to dummy
Failed while bringing device to "any" state</msg>
<status status="FAIL" starttime="20200711 20:14:14.941" endtime="20200711 20:15:40.058"></status>
</kw>
<status status="FAIL" starttime="20200711 20:14:13.406" endtime="20200711 20:15:40.059" critical="yes">ConnectionError: failed to connect to dummy
Failed while bringing device to "any" state</status>
</test>
<test id="s1-t2" name="Verify Interfaces">
<kw name="run verification &quot;Verify_IpInterfaceBrief&quot; on device &quot;R1&quot;" library="genie.libs.robot.GenieRobot">
<doc>Call any verification defined in the verification datafile
on device</doc>
<msg timestamp="20200711 20:15:55.922" level="FAIL">Could not find 'Verify_IpInterfaceBrief'</msg>
<status status="FAIL" starttime="20200711 20:15:40.061" endtime="20200711 20:15:55.922"></status>
</kw>
<status status="FAIL" starttime="20200711 20:15:40.060" endtime="20200711 20:15:55.922" critical="yes">Could not find 'Verify_IpInterfaceBrief'</status>
</test>
<status status="FAIL" starttime="20200711 20:14:12.479" endtime="20200711 20:15:55.923"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="2">Critical Tests</stat>
<stat pass="0" fail="2">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="2" id="s1" name="Validate">Validate</stat>
</suite>
</statistics>
<errors>
</errors>
</robot>
